### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [luckyorange/integration-google-tag-manager#1]
https://github.com/luckyorange/integration-google-tag-manager/blob/45ad102311a4a3b435452733a5d977b52caaf2b9/template.tpl#L48

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by hgascoigne** [comment]
Hey @philpott, I've gone ahead and updated the template to incorporate the use of `encodeUriComponent` for building out the query parameters.
